### ISSUE TITLE
Failures for all CSS examples from HTML spec

### ISSUE THREAD

**Issue by sideshowbarker** [tabatkins/highlighter#5]
In the HTML spec, there are 29 examples of CSS stylesheet fragments, and processing of any of them in the highlighter fails with the same stack trace and error message:

    AssertionError: token type must be simple type or callable, not Token.Comment

Example input:
```
$ echo '["pre",{"class": "css"},"img { width: 300px; height: 300px }\n@media (min-width: 32em) { img { width: 500px; height:300px } }\n@media (min-width: 45em) { img { width: 700px; height:400px } }"]' \
  | ./highlighter/__init__.py css
```
…and resulting stack trace and error message:

```
Traceback (most recent call last):
  File "./highlighter/__init__.py", line 47, in <module>
    cli()
  File "./highlighter/__init__.py", line 35, in cli
    html,css = highlight(input, **options)
  File "/Users/mike/workspace/html-build/highlighter/highlighter/highlight.py", line 26, in highlight
    html = highlightEl(html, lang)
  File "/Users/mike/workspace/html-build/highlighter/highlighter/highlight.py", line 77, in highlightEl
    coloredText = highlightWithPygments(text, lang)
  File "/Users/mike/workspace/html-build/highlighter/highlighter/highlight.py", line 162, in highlightWithPygments
    lexer = lexerFromLang(lang)
  File "/Users/mike/workspace/html-build/highlighter/highlighter/highlight.py", line 334, in lexerFromLang
    return customLexers[lang]()
  File "/Users/mike/workspace/html-build/highlighter/highlighter/highlight.py", line 13, in loadCSSLexer
    return CSSLexer()
  File "/Users/mike/workspace/html-build/highlighter/highlighter/pygments/pygments/lexer.py", line 580, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "/Users/mike/workspace/html-build/highlighter/highlighter/pygments/pygments/lexer.py", line 519, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "/Users/mike/workspace/html-build/highlighter/highlighter/pygments/pygments/lexer.py", line 503, in _process_state
    token = cls._process_token(tdef[1])
  File "/Users/mike/workspace/html-build/highlighter/highlighter/pygments/pygments/lexer.py", line 432, in _process_token
    'token type must be simple type or callable, not %r' % (token,)
AssertionError: token type must be simple type or callable, not Token.Comment
```

**Comment by tabatkins** [comment]
Ugh, this was a *really* stupid bug, but luckily on Pygments' part, not mine.

Issue is that Pygments does its own imports badly, relying on you having globally installed the package - it does `from pygments.foo import bar` when it should be doing `from .foo import bar`.

So, since Highlighter includes its own *local* copy of Pygments, when it executes it uses classes from the local version (like `Token.Comment`), but then Pygments itself at some point type-checks the value and compares it to the *global* version's `_TokenType` superclass that it's imported. This obviously fails, as the local classes are descended from the local `_TokenType` instead.

I fixed it by switching the imports to the proper relative syntax, and am seeing if I can fix it upstream too.

**Comment by sideshowbarker** [comment]
Thanks much for the fix. I tested with the HTML spec in my environment and confirmed we now get the  expected output for those CSS examples.

So as far as the content of the HTML spec goes, the only remaining failures are for the WebIDL cases itemized in #4.
